In [9]:
PV = 100
f = 1.03
n = 2

In [10]:
FV  = PV * f**n
FV

106.08999999999999

In [11]:
import math

In [12]:
FV = PV * math.pow(f,n)
FV

106.08999999999999

In [13]:
math.sqrt(FV/PV) - 1

0.030000000000000027

In [14]:
math.sin(3)

0.1411200080598672

In [15]:
math.e

2.718281828459045

In [8]:
math.pi

3.141592653589793

In [17]:
import math as ma

In [18]:
ma.pi

3.141592653589793

In [19]:
from math import sqrt

In [20]:
sqrt(FV/PV) -1

0.030000000000000027

In [23]:
import numpy as np

In [24]:
np.sqrt(FV/PV)

np.float64(1.03)

In [25]:
PV * np.power(f, n)

np.float64(106.08999999999999)

# Numpy Arrays

In [26]:
import numpy as np

In [29]:
cf = [50, 100, 120, 150, 200, 300]
cf

[50, 100, 120, 150, 200, 300]

In [31]:
cf_a = np.array(cf)
cf_a

array([ 50, 100, 120, 150, 200, 300])

In [32]:
type(cf_a)

numpy.ndarray

In [33]:
cf - 20

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [34]:
cf * 1.1

TypeError: can't multiply sequence by non-int of type 'float'

In [35]:
cf * 2

[50, 100, 120, 150, 200, 300, 50, 100, 120, 150, 200, 300]

In [36]:
cf_new = []
for i in cf:
    cf_new.append(i - 20)
cf_new

[30, 80, 100, 130, 180, 280]

In [37]:
cf_a - 20

array([ 30,  80, 100, 130, 180, 280])

In [38]:
cf_a * 1.1

array([ 55., 110., 132., 165., 220., 330.])

In [39]:
cf_a * 2

array([100, 200, 240, 300, 400, 600])

In [40]:
cf_a

array([ 50, 100, 120, 150, 200, 300])

In [41]:
add_cf = np.array([10,20, -10, 30, 10, -5])
add_cf

array([ 10,  20, -10,  30,  10,  -5])

In [42]:
cf_a + add_cf

array([ 60, 120, 110, 180, 210, 295])

In [43]:
cf_a.dtype

dtype('int64')

In [44]:
l = [100, 20.5, 30, 10.7, True, "Apple"]
l

[100, 20.5, 30, 10.7, True, 'Apple']

In [45]:
a = np.array(l)
a

array(['100', '20.5', '30', '10.7', 'True', 'Apple'], dtype='<U32')

In [46]:
for element in a:
    print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Indexing and Slicing Numpy Arrays

In [47]:
import numpy as np

In [49]:
cf = np.array([50, 100, 120, 150, 200, 300])
cf

array([ 50, 100, 120, 150, 200, 300])

In [50]:
cf[0]

np.int64(50)

In [51]:
cf[2]

np.int64(120)

In [52]:
cf[-1]

np.int64(300)

In [53]:
cf[-3]

np.int64(150)

In [54]:
cf[2:4]

array([120, 150])

In [55]:
cf[:3]

array([ 50, 100, 120])

In [56]:
cf[2:]

array([120, 150, 200, 300])

In [57]:
cf[:-1]

array([ 50, 100, 120, 150, 200])

In [58]:
cf[-2:]

array([200, 300])

In [59]:
cf[1:5:2]

array([100, 150])

In [60]:
cf[::-1]

array([300, 200, 150, 120, 100,  50])

# Vectorized Operations with Numpy

In [61]:
import numpy as np

In [62]:
cf = np.array([50, 100, 120, 150, 200, 300])
cf

array([ 50, 100, 120, 150, 200, 300])

In [63]:
cf * 1.1

array([ 55., 110., 132., 165., 220., 330.])

In [64]:
cf + 20

array([ 70, 120, 140, 170, 220, 320])

In [66]:
cf_add = np.array([10, 20, 5, -10, 20, 10])
cf_add

array([ 10,  20,   5, -10,  20,  10])

In [67]:
cf + cf_add

array([ 60, 120, 125, 140, 220, 310])

The XYZ Company evaluates to buy an additional machine that will increase future profits/cashflows by
- 20 USD in t1,
- 50 USD in t2,
- 70 USD in t3,
- 100 USD in t4,
- 50 USD in t5. (each cf at period's end)

The machine costs 200 USD (Investment in to). Calculate the **Project's NPV** and evaluate whether XYZ should pursue the project.
XYZ's required rate of return (Cost of Capital) is 6% p.a.

In [68]:
cf = np.array([-200, 20, 50, 70, 100, 50])
r = 0.06
f = 1 + r

In [69]:
n = np.array([0, 1, 2, 3, 4, 5])
n

array([0, 1, 2, 3, 4, 5])

In [70]:
cf / f**n

array([-200.        ,   18.86792453,   44.499822  ,   58.77334981,
         79.20936632,   37.36290864])

In [71]:
pv_array = cf / f**n
pv_array

array([-200.        ,   18.86792453,   44.499822  ,   58.77334981,
         79.20936632,   37.36290864])

In [72]:
NPV = pv_array.sum()
NPV

np.float64(38.71337130837991)

In [73]:
(cf / f**n).sum()

np.float64(38.71337130837991)

In [74]:
NPV = 0
for i in range(len(cf)):
    NPV +=  cf[i] / f**(i)
print(NPV)

38.71337130837991


Changing Elements in Numpy Arrays & Mutability

In [75]:
import numpy as np

In [76]:
cf = np.array([100, 10, 20, 50, 30, 25])

In [77]:
cf[0] = 95

In [78]:
cf

array([95, 10, 20, 50, 30, 25])

In [79]:
cf[1:] = [40, 40, 40, 40, 40]

In [80]:
cf

array([95, 40, 40, 40, 40, 40])

In [83]:
cf[1:] = 45

In [85]:
cf

array([95, 45, 45, 45, 45, 45])

In [86]:
cf + 20

array([115,  65,  65,  65,  65,  65])

In [87]:
cf

array([95, 45, 45, 45, 45, 45])

In [88]:
cf = cf + 20

In [89]:
cf

array([115,  65,  65,  65,  65,  65])

In [90]:
cf1 = np.array([100, 10, 20, 50, 30, 25])

In [91]:
cf2 = cf1

In [92]:
cf1 = np.array([100, 10, 20, 50, 30, 25])

In [93]:
cf2 = cf1[:]